import type { Dispatch, SetStateAction } from 'react';
import type { CRTColorMode, CRTSettings } from '../crt/CRTFilter';
import { RESOLUTIONS, type ResolutionId, type StoredSettings, type TabPlacement } from '../crt/settings';
import { COLOR_PROFILES } from '../terminal-color-profiles';
import { Knob, formatValue } from './Knob';
import type { RenderStats } from '../terminal/TerminalRenderer';

type NumericKey = Exclude<keyof CRTSettings, 'crtEmulation' | 'colorProfile' | 'consoleFont' | 'bezelGlow' | 'showBezel' | 'antiAliasedPixels' | 'colorMode' | 'bloomAlgorithm'>;
const SHOW_TELEMETRY = false;
const controls: Record<string, { key: NumericKey; label: string; min: number; max: number; step: number }[]> = { Geometry: [{ key: 'curvature', label: 'Curvature', min: 0, max: .5, step: .01 }, { key: 'vignette', label: 'Vignette', min: 0, max: 1, step: .05 }], Raster: [{ key: 'scanlineCount', label: 'Scanline count', min: 0, max: 768, step: 10 }, { key: 'scanlineIntensity', label: 'Scanline intensity', min: 0, max: 1, step: .05 }, { key: 'beamModulation', label: 'Beam modulation', min: 0, max: 1, step: .05 }], Light: [{ key: 'aberration', label: 'RGB split', min: 0, max: 5, step: .1 }, { key: 'bloom', label: 'Bloom', min: 0, max: 1, step: .05 }, { key: 'glow', label: 'Screen glow', min: 0, max: 2, step: .05 }, { key: 'phosphor', label: 'Phosphor / grain', min: 0, max: 1, step: .05 }], 'Final image': [{ key: 'imageBrightness', label: 'Image brightness', min: .5, max: 1.5, step: .05 }, { key: 'imageContrast', label: 'Image contrast', min: .5, max: 1.5, step: .05 }], Temporal: [{ key: 'persistence', label: 'Phosphor trail', min: 0, max: 1, step: .05 }, { key: 'persistenceIntensity', label: 'Trail intensity', min: 0, max: 4, step: .05 }, { key: 'breathing', label: 'HV breathing', min: 0, max: 1, step: .05 }] };

export function SettingsPanel({ stored, setStored, monospaceFonts, terminalSize, fps, renderStats, onReset }: { stored: StoredSettings; setStored: Dispatch<SetStateAction<StoredSettings>>; monospaceFonts: string[]; terminalSize: { cols: number; rows: number }; fps: number; renderStats: RenderStats; onReset: () => void }) {
  const update = (key: NumericKey, value: number) => setStored((current) => ({ ...current, crt: { ...current.crt, [key]: value } }));
  const averageCanvasMs = renderStats.redraws ? renderStats.canvasMs / renderStats.redraws : 0;
  return <aside className="settings-panel"><header><p className="eyebrow">SCANLINE TERM</p><h1>CRT display lab</h1><p className="display-status">CONSOLE BUFFER: {terminalSize.cols} × {terminalSize.rows} · FPS: {fps}{SHOW_TELEMETRY && <><br />REDRAWS: {renderStats.redraws * 2}/s · CANVAS: {averageCanvasMs.toFixed(1)} ms · GLYPHS: {renderStats.glyphs * 2}/s</>}</p></header>
    <label className="resolution-control">Virtual resolution<select value={stored.resolution} data-testid="resolution-select" onChange={(event) => setStored((current) => ({ ...current, resolution: event.target.value as ResolutionId }))}>{RESOLUTIONS.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
    <label className="resolution-control">Tab placement<select value={stored.tabPlacement} onChange={(event) => setStored((current) => ({ ...current, tabPlacement: event.target.value as TabPlacement }))}><option value="top">Above monitor</option><option value="left">Left of monitor</option></select></label>
    <label className="resolution-control">Settings scale<select value={stored.settingsScale} onChange={(event) => setStored((current) => ({ ...current, settingsScale: Number(event.target.value) }))}>{[.75,.9,1,1.1,1.25,1.5].map((scale) => <option key={scale} value={scale}>{Math.round(scale * 100)}%</option>)}</select></label>
    <label className="check-control"><input type="checkbox" checked={stored.hideTabsWhenSingleSession} onChange={(event) => setStored((current) => ({ ...current, hideTabsWhenSingleSession: event.target.checked }))} />Hide tabs when single session</label>
    <label className="check-control"><input type="checkbox" checked={stored.globalHotkeyEnabled} onChange={(event) => setStored((current) => ({ ...current, globalHotkeyEnabled: event.target.checked }))} />Global hotkey: Win+~</label>
    <label className="resolution-control">Color mode<select value={stored.crt.colorMode} data-testid="color-mode-select" onChange={(event) => setStored((current) => ({ ...current, crt: { ...current.crt, colorMode: event.target.value as CRTColorMode } }))}><option value="color">Color</option><option value="bw">B&amp;W</option><option value="green">Green</option><option value="amber">Amber</option><option value="blue">Phosphor Blue</option></select></label>
    <label className="resolution-control">Color profile<select value={stored.crt.colorProfile} data-testid="color-profile-select" onChange={(event) => setStored((current) => ({ ...current, crt: { ...current.crt, colorProfile: event.target.value as CRTSettings['colorProfile'] } }))}>{COLOR_PROFILES.map((profile) => <option key={profile.id} value={profile.id}>{profile.label}</option>)}</select></label>
    <label className="resolution-control">Bloom algorithm<select value={stored.crt.bloomAlgorithm} onChange={(event) => setStored((current) => ({ ...current, crt: { ...current.crt, bloomAlgorithm: event.target.value as CRTSettings['bloomAlgorithm'] } }))}><option value="soft">Soft blur</option><option value="spiral">Spiral (legacy)</option></select></label>
    <label className="resolution-control">Console font<select value={stored.crt.consoleFont} onChange={(event) => setStored((current) => ({ ...current, crt: { ...current.crt, consoleFont: event.target.value } }))}>{!monospaceFonts.includes(stored.crt.consoleFont) && <option value={stored.crt.consoleFont}>{stored.crt.consoleFont} (fallback)</option>}{monospaceFonts.map((font) => <option key={font} value={font}>{font}</option>)}</select></label>
    <label className="resolution-control">Console font size<select value={stored.crt.consoleFontSize} onChange={(event) => setStored((current) => ({ ...current, crt: { ...current.crt, consoleFontSize: Number(event.target.value) } }))}>{[6,7,8,9,10,11,12,14,16,18,20,24,28,32].map((size) => <option key={size} value={size}>{size} px</option>)}</select></label>
    {Object.entries(controls).map(([group, groupControls]) => <fieldset className="knob-group" key={group}><legend>{group}</legend>{groupControls.map((control) => <label className="slider-control" key={control.key}><span>{control.label}<output>{formatValue(stored.crt[control.key])}</output></span><Knob {...control} value={stored.crt[control.key]} onChange={(value) => update(control.key, value)} /></label>)}</fieldset>)}
    <fieldset className="knob-group"><legend>Surface</legend><label className="slider-control"><span>Background desaturation<output>{formatValue(stored.crt.backgroundDesaturation)}</output></span><Knob value={stored.crt.backgroundDesaturation} min={0} max={1} step={.05} label="Background desaturation" onChange={(value) => update('backgroundDesaturation', value)} /></label></fieldset>
    <fieldset><legend>Display</legend>{([['crtEmulation','CRT Emulation'],['bezelGlow','Bezel glow'],['showBezel','Monitor frame'],['antiAliasedPixels','Anti-moiré pixels']] as const).map(([key,label]) => <label className="check-control" key={key}><input type="checkbox" checked={stored.crt[key]} data-testid={key === 'crtEmulation' ? 'control-crtEmulation' : undefined} onChange={(event) => setStored((current) => ({ ...current, crt: { ...current.crt, [key]: event.target.checked } }))} />{label}</label>)}</fieldset>
    <button type="button" className="reset-button" onClick={onReset}>Reset defaults</button><footer>v0.2 · ConPTY · ANSI screen buffer</footer></aside>;
}
