/* eslint-disable react-hooks/refs */
import { useCallback, useEffect, useRef, useState, type ClipboardEvent, type MouseEvent, type WheelEvent } from 'react';
import { getCurrentWindow } from '@tauri-apps/api/window';
import { invoke, isTauri } from '@tauri-apps/api/core';
import type { CRTSettings } from '../crt/CRTFilter';
import type { Resolution } from './TerminalRenderer';
import { TerminalRenderer, terminalDimensions, type CopyPoint } from './TerminalRenderer';
import { TerminalSession, initialProfile, type TerminalSize } from './TerminalSession';
import { terminalKey } from './terminal-input';
import { terminalMouse, type MouseTrackingMode } from './terminal-mouse';
import { win32InputKey } from '../win32-input';

export function useTerminal({ settings, resolution, onError, onToggleSettings }: { settings: CRTSettings; resolution: Resolution; onError: (message: string) => void; onToggleSettings: () => void }) {
  const [live, setLive] = useState(false); const [size, setSize] = useState<TerminalSize>({ cols: 0, rows: 0 }); const [fonts, setFonts] = useState(['Consolas']);
  const renderer = useRef<TerminalRenderer | null>(null); if (!renderer.current) renderer.current = new TerminalRenderer();
  const settingsRef = useRef(settings); const resolutionRef = useRef(resolution); const outputRef = useRef<HTMLCanvasElement | null>(null); const sessionRef = useRef<TerminalSession | null>(null); const pressed = useRef(new Set<number>()); const copyStart = useRef<CopyPoint | null>(null); const copyMode = useRef(false); const menu = useRef(false); const fullscreen = useRef(false);
  settingsRef.current = settings; resolutionRef.current = resolution;
  useEffect(() => { if (!isTauri()) return; void invoke<string[]>('list_monospace_fonts').then((items) => setFonts([...new Set(['Consolas', ...items])])).catch((reason) => onError(`Could not list system fonts: ${String(reason)}`)); }, [onError]);
  useEffect(() => { const session = new TerminalSession(onError, (nextLive, nextSize) => { setLive(nextLive); setSize(nextSize); }); sessionRef.current = session; const start = window.setTimeout(() => { const source = renderer.current!.sourceCanvas; const dimensions = terminalDimensions(source.width || resolutionRef.current.width || 1, source.height || resolutionRef.current.height || 1, settingsRef.current.consoleFontSize, settingsRef.current.consoleFont); void session.start(dimensions, initialProfile(settingsRef.current.colorProfile)).then(() => renderer.current!.bindTerminal(session.terminal)); }); return () => { window.clearTimeout(start); session.dispose(); renderer.current!.dispose(); sessionRef.current = null; }; }, [onError]);
  const resizeSource = useCallback((output: HTMLCanvasElement) => { outputRef.current = output; renderer.current!.resizeSource(resolutionRef.current, output); const source = renderer.current!.sourceCanvas; sessionRef.current?.resize(terminalDimensions(source.width, source.height, settingsRef.current.consoleFontSize, settingsRef.current.consoleFont)); }, []);
  useEffect(() => { const output = outputRef.current; if (output) resizeSource(output); }, [resizeSource, settings.consoleFont, settings.consoleFontSize, resolution]);
  useEffect(() => { renderer.current!.markDirty(); }, [settings.colorProfile, settings.consoleFont, settings.consoleFontSize]);
  const cell = (event: MouseEvent<HTMLCanvasElement> | WheelEvent<HTMLCanvasElement>) => renderer.current!.cellAtPoint(event.clientX, event.clientY, event.currentTarget, settingsRef.current);
  const copyPoint = (point: { col: number; row: number }): CopyPoint => { const terminal = sessionRef.current!.terminal!; return { row: Math.max(terminal.buffer.active.viewportY, terminal.buffer.active.viewportY + point.row - 1), column: Math.max(0, point.col - 1) }; };
  const sendMouse = (event: MouseEvent<HTMLCanvasElement> | WheelEvent<HTMLCanvasElement>, action: Parameters<typeof terminalMouse>[0]['action'], button?: 0 | 1 | 2) => { const session = sessionRef.current; const terminal = session?.terminal; const tracking = terminal?.modes.mouseTrackingMode as MouseTrackingMode | undefined; if (!session || !terminal || !tracking || tracking === 'none' || (tracking === 'x10' && (action !== 'press' || event.ctrlKey || event.altKey || event.shiftKey)) || (tracking === 'vt200' && action === 'move')) return false; const point = cell(event); if (!point) return false; event.preventDefault(); session.sendInput(terminalMouse({ ...point, action, button, sgr: session.sgrMouseMode, ctrlKey: event.ctrlKey, altKey: event.altKey, shiftKey: event.shiftKey })); return true; };
  const copy = async (start: CopyPoint, end: CopyPoint) => { const terminal = sessionRef.current?.terminal; if (!terminal) return; const [first,last] = start.row < end.row || start.row === end.row && start.column <= end.column ? [start,end] : [end,start]; const text = Array.from({ length: last.row - first.row + 1 }, (_, index) => { const row = first.row + index; return terminal.buffer.active.getLine(row)?.translateToString(index === last.row - first.row, row === first.row ? first.column : 0, row === last.row ? last.column + 1 : terminal.cols) ?? ''; }).join('\r\n').replace(/(?:\r\n|\r|\n)$/, ''); if (text) await navigator.clipboard.writeText(text); };
  useEffect(() => { const down = async (event: KeyboardEvent) => { const session = sessionRef.current; const terminal = session?.terminal; if (event.key === 'ContextMenu') menu.current = true; if (menu.current && event.code === 'KeyS') { event.preventDefault(); if (!event.repeat) onToggleSettings(); return; } if (menu.current && event.code === 'KeyV') { event.preventDefault(); if (!event.repeat) navigator.clipboard.readText().then((input) => session?.sendInput(input)).catch((reason) => onError(`Clipboard paste failed: ${String(reason)}`)); return; } if (menu.current && event.code === 'KeyC') { event.preventDefault(); if (!event.repeat) copyMode.current = true; return; } if (menu.current && (event.code === 'PageUp' || event.code === 'PageDown')) { event.preventDefault(); if (terminal && terminal.buffer.active === terminal.buffer.normal) terminal.scrollLines((event.code === 'PageUp' ? -1 : 1) * (terminal.rows - 1)); return; } if (event.altKey && event.key === 'Enter' && isTauri()) { event.preventDefault(); fullscreen.current = true; if (!event.repeat) try { const window = getCurrentWindow(); await window.setFullscreen(!(await window.isFullscreen())); } catch (reason) { onError(`Fullscreen toggle failed: ${String(reason)}`); } return; } if (!session?.live || !terminal) return; const input = session.win32InputMode ? win32InputKey(event, true) : terminalKey(event, terminal.modes); event.preventDefault(); if (input) { terminal.scrollToBottom(); session.sendInput(input); } }; const up = (event: KeyboardEvent) => { if (event.key === 'ContextMenu') menu.current = false; if (fullscreen.current && event.key === 'Enter') { fullscreen.current = false; event.preventDefault(); return; } const session = sessionRef.current; if (!session?.live || !session.terminal) return; event.preventDefault(); if (session.win32InputMode) session.sendInput(win32InputKey(event, false)); }; window.addEventListener('keydown', down, true); window.addEventListener('keyup', up, true); return () => { window.removeEventListener('keydown', down, true); window.removeEventListener('keyup', up, true); }; }, [onError, onToggleSettings]);
  return { renderer: renderer.current, live, size, fonts, resizeSource, canvasProps: { onWheel: (event: WheelEvent<HTMLCanvasElement>) => { const terminal = sessionRef.current?.terminal; if (!terminal || event.deltaY === 0) return; if (sendMouse(event, event.deltaY < 0 ? 'wheel-up' : 'wheel-down')) return; event.preventDefault(); if (terminal.buffer.active === terminal.buffer.normal) terminal.scrollLines(Math.sign(event.deltaY) * 3); }, onMouseDown: (event: MouseEvent<HTMLCanvasElement>) => { const terminal = sessionRef.current?.terminal; if (terminal && ((copyMode.current && event.button === 0) || event.button === 1)) { const point = cell(event); if (point) { event.preventDefault(); copyStart.current = copyPoint(point); renderer.current!.setSelection({ start: copyStart.current, end: copyStart.current }); } return; } if (event.button <= 2 && sendMouse(event, 'press', event.button as 0|1|2)) pressed.current.add(event.button); }, onMouseMove: (event: MouseEvent<HTMLCanvasElement>) => { const terminal = sessionRef.current?.terminal; if (terminal && copyStart.current && event.buttons) { const point = cell(event); if (point) renderer.current!.setSelection({ start: copyStart.current, end: copyPoint(point) }); return; } const tracking = terminal?.modes.mouseTrackingMode as MouseTrackingMode | undefined; if (tracking && tracking !== 'none' && !(tracking === 'drag' && pressed.current.size === 0) && tracking !== 'x10' && tracking !== 'vt200') sendMouse(event, 'move', pressed.current.values().next().value as 0|1|2|undefined); }, onMouseUp: (event: MouseEvent<HTMLCanvasElement>) => { const terminal = sessionRef.current?.terminal; if (terminal && copyStart.current) { const start = copyStart.current; copyStart.current = null; copyMode.current = false; const point = cell(event); if (point) void copy(start, copyPoint(point)).catch((reason) => onError(`Clipboard copy failed: ${String(reason)}`)); renderer.current!.setSelection(null); return; } if (event.button <= 2) { sendMouse(event, 'release', event.button as 0|1|2); pressed.current.delete(event.button); } }, onMouseLeave: (event: MouseEvent<HTMLCanvasElement>) => { for (const button of pressed.current) sendMouse(event, 'release', button as 0|1|2); pressed.current.clear(); }, onContextMenu: (event: MouseEvent<HTMLCanvasElement>) => event.preventDefault(), onPaste: (event: ClipboardEvent<HTMLCanvasElement>) => { const input = event.clipboardData.getData('text'); if (!input) return; event.preventDefault(); sessionRef.current?.terminal?.scrollToBottom(); sessionRef.current?.sendInput(input); } } };
}
